const models = [
  ["Cohere Transcribe","Cohere","Open Weight","2B · INT8 / FP16","1.8–2.4 GB","Pixel 7a / Galaxy A55 · $300–400","Real-time, 14-language offline speech recognition and dictation.","https://cohere.com/transcribe"],
  ["Tiny Aya","Cohere Labs","Open Weight","3.3B / 3B active · INT4 GGUF","2.2–3.0 GB","Poco F6 Pro / OnePlus 12R · $380–500","High-speed multilingual translation across 70+ languages.","https://docs.cohere.com/docs/tiny-aya"],
  ["Apple Intelligence Model","Apple","Closed (OS)","3.0B · mixed 3b/4b","~2.5–3.0 GB","iPhone 15 Pro / iPhone 16 · $799–999","Siri orchestration, Smart Reply, summaries, writing tools, photo indexing.","https://developer.apple.com/apple-intelligence/"],
  ["Gemini Nano (v1/v2)","Google","Closed (OS)","1.8B–3.2B · INT4","~3.0–4.0 GB","Pixel 8a / Pixel 9 / Galaxy S24 · $499–799","Smart Reply, live transcription, Magic Compose, call assistant tools.","https://store.google.com/us/magazine/gemini-nano-offline?hl=en-US"],
  ["SmolLM2","Hugging Face","Open Weight","135M / 360M / 1.7B · INT4","0.3–1.4 GB","Galaxy A15 / Moto G Power · $150–250","Fast text generation, classification, and mobile text utilities.","https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct"],
  ["Llama 3.2 Mobile","Meta","Open Weight","1B & 3B · INT4","1.2–2.8 GB","Poco F6 / Xiaomi 13T / Galaxy S23 · $350–550","Offline assistants, document summaries, and private note querying.","https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"],
  ["Qwen 2.5 / Qwen 3","Alibaba","Open Weight","0.5B / 1.5B / 3B · INT4","0.8–2.8 GB","Nothing Phone (2a) / Redmi Note 13 Pro · $250–380","Multilingual assistant workflows and mobile code generation.","https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF"],
  ["Gemma 2 / Gemma 3n","Google","Open Weight","1B / 2B / 4B · INT4 LiteRT","1.0–3.2 GB","Pixel 7a / Motorola Edge 50 · $300–450","Local search, personal-note RAG, and offline agent workflows.","https://ai.google.dev/gemma"],
  ["Phi-3.5 / Phi-4 Mini","Microsoft","Open Weight","3.8B · INT4 ONNX","3.0–3.8 GB","OnePlus 12 / iQOO 12 / iPhone 15 Pro · $600–850","Math, multi-step reasoning, code parsing, and JSON tool calling.","https://huggingface.co/microsoft/Phi-3.5-mini-instruct"],
  ["MobileLLM / Pro","Meta Research","Open Weight","125M / 350M / 1B · INT4 / INT8","0.4–1.2 GB","Entry phones / wearables · $100–200","Text parsing, ambient commands, and low-power text manipulation.","https://github.com/facebookresearch/MobileLLM"],
  ["Desert Ant Micro-SDKs","Desert Ant Labs","Commercial SDK","2M–400M · custom","50–500 MB","Modern iOS / Android · $100+","PII redaction, speech-to-text, and photo scoring micro-tasks.","https://desertant.com/"],
  ["Whisper Tiny / Base","OpenAI / CTranslate2","Open Weight","39M–74M · INT8 / FP16","150–400 MB","Pixel 6a / Galaxy A54 · $200–350","Continuous voice-to-text, meeting transcription, and voice notes.","https://aihub.qualcomm.com/models/whisper_tiny"],
  ["Picovoice Porcupine","Picovoice","Commercial SDK","<10M · micro-weights","<50 MB","Any phone or IoT device · $50–150","Always-on wake-word activation and offline voice intent classification.","https://picovoice.ai/"],
  ["Liquid LFM2 / LFM2.5","Liquid AI","Open Weight","230M / 350M / 1.2B / 2.6B · INT4","0.3–2.2 GB","Mid-range to flagship · $200–700","Long-context processing, tool calling, and efficient on-device reasoning.","https://demos.liquid.ai/"],
  ["Mistral NeMo 8B","Mistral AI / NVIDIA","Open Weight","8B · INT3 / INT4 GGUF","6.0–7.5 GB","OnePlus 12 / S24 Ultra / iPhone 16 Pro · $800+","Coding, long-form multilingual reasoning, and enterprise function calling.","https://huggingface.co/nvidia/Mistral-NeMo-Minitron-8B-Base"]
];
const rows=document.querySelector('#modelRows'),search=document.querySelector('#search'),count=document.querySelector('#resultCount'),ramFilter=document.querySelector('#ramFilter'),dialog=document.querySelector('#modelDialog'),dialogContent=document.querySelector('#dialogContent');let active='all',selectedNames=null;
function memoryFloor(memory){const match=memory.match(/[\d.]+/);return match?Number(match[0]):99}
function eligible(m){const ram=Number(ramFilter.value);return (!ram||memoryFloor(m[4])<=ram)}
function openDetail(name){const m=models.find(model=>model[0]===name);if(!m)return;dialogContent.innerHTML=`<p class="eyebrow">Model detail</p><h2>${m[0]}</h2><p class="dialog-provider">${m[1]} · ${m[2]}</p><dl><div><dt>Mobile profile</dt><dd>${m[3]}</dd></div><div><dt>Reported working memory</dt><dd>${m[4]}</dd></div><div><dt>Minimum spec phones</dt><dd>${m[5]}</dd></div><div><dt>Primary offline use</dt><dd>${m[6]}</dd></div></dl><p class="dialog-note">Treat the phone guidance as a practical starting point, not a device certification. Runtime, context length, and background memory use can materially change results.</p><a class="source-button" href="${m[7]}" target="_blank" rel="noreferrer">Open primary source ↗</a>`;dialog.showModal()}
function render(){const q=search.value.toLowerCase();const shown=models.filter(m=>(active==='all'||m[2]===active)&&eligible(m)&&(!selectedNames||selectedNames.includes(m[0]))&&m.join(' ').toLowerCase().includes(q));rows.innerHTML=shown.map(m=>{const c=m[2]==='Open Weight'?'open':m[2]==='Closed (OS)'?'closed':'sdk';return `<tr><td class="model"><button class="model-open" data-name="${m[0]}">${m[0]} ↗</button><span class="provider">${m[1]}</span></td><td><span class="pill ${c}">${m[2]}</span></td><td>${m[3]}</td><td>${m[4]}</td><td>${m[5]}</td><td class="use">${m[6]}</td></tr>`}).join('');count.textContent=`${shown.length} of ${models.length} models`}
document.querySelector('#heroStats').innerHTML=`<div class="stat"><b>${models.length}</b><span>models indexed</span></div><div class="stat"><b>${models.filter(m=>m[2]==='Open Weight').length}</b><span>open-weight options</span></div><div class="stat"><b>50 MB–7.5 GB</b><span>reported memory range</span></div>`;
const sourceType={"Cohere Transcribe":"Product documentation","Tiny Aya":"Technical documentation","Apple Intelligence Model":"Platform documentation","Gemini Nano (v1/v2)":"Product documentation","SmolLM2":"Model card","Llama 3.2 Mobile":"Model card","Qwen 2.5 / Qwen 3":"Model card","Gemma 2 / Gemma 3n":"Technical documentation","Phi-3.5 / Phi-4 Mini":"Model card","MobileLLM / Pro":"Research repository","Desert Ant Micro-SDKs":"SDK documentation","Whisper Tiny / Base":"Model documentation","Picovoice Porcupine":"SDK documentation","Liquid LFM2 / LFM2.5":"Product documentation","Mistral NeMo 8B":"Model card"};document.querySelector('#sourceRows').innerHTML=models.map(m=>`<tr><td>${m[0]}</td><td>${m[1]}</td><td>${sourceType[m[0]]}</td><td><a class="source-registry-link" href="${m[7]}" target="_blank" rel="noreferrer">Open source ↗</a></td></tr>`).join('');
const benchmarks={
  "Cohere Transcribe":{label:"Open ASR Leaderboard · average WER",value:"5.42% ↓",note:"Cohere’s reported English-leaderboard snapshot for the 2B Transcribe model. Lower word error rate is better; this is not a phone-runtime result.",source:"https://cohere.com/blog/transcribe"},
  "Tiny Aya":{label:"FLORES (66) · ChrF",value:"43.5",note:"Tiny Aya Global’s mean English-to-target translation score across 66 focus languages, as reported in the technical report. Higher is better.",source:"https://arxiv.org/abs/2603.11510"},
  "Apple Intelligence Model":{label:"Published benchmark",value:"No public standard-score table",note:"Apple documents capabilities and supported hardware, but does not publish a model-card benchmark table for the on-device system model.",source:"https://developer.apple.com/apple-intelligence/"},
  "Gemini Nano (v1/v2)":{label:"Published benchmark",value:"No public standard-score table",note:"Google’s consumer documentation describes on-device features; it does not supply a reproducible benchmark table for the deployed Nano variants.",source:"https://store.google.com/us/magazine/gemini-nano-offline?hl=en-US"},
  "SmolLM2":{label:"HellaSwag · 0-shot accuracy",value:"66.1%",note:"SmolLM2-1.7B-Instruct, reported by Hugging Face with Lighteval. This is an instruction-model result, not a phone-runtime measurement.",source:"https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct"},
  "Llama 3.2 Mobile":{label:"MMLU · 5-shot accuracy",value:"63.4%",note:"Llama 3.2 3B bf16 instruction model, reported by Meta. Quantized mobile variants have separately reported results and should not be substituted for this score.",source:"https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"},
  "Qwen 2.5 / Qwen 3":{label:"MMLU-redux",value:"64.4%",note:"Qwen2.5-3B result reported in Qwen’s official evaluation table. MMLU-redux is not directly interchangeable with MMLU.",source:"https://huggingface.co/Qwen/Qwen2.5-Omni-3B"},
  "Gemma 2 / Gemma 3n":{label:"MMLU · 0-shot accuracy",value:"64.9%",note:"Gemma 3n E4B instruction-tuned variant, reported in Google’s model card. Gemma 2 and other Gemma 3n variants should not inherit this score.",source:"https://ai.google.dev/gemma/docs/gemma-3n/model_card"},
  "Phi-3.5 / Phi-4 Mini":{label:"MMLU · 5-shot accuracy",value:"69.0%",note:"Phi-3.5-mini-instruct, reported by Microsoft under completion format. It is not an on-device latency or energy measurement.",source:"https://huggingface.co/microsoft/Phi-3.5-mini-instruct"},
  "MobileLLM / Pro":{label:"8-task commonsense average · 1B",value:"57.3%",note:"MobileLLM-1B zero-shot mean across ARC-E, ARC-C, BoolQ, PIQA, SIQA, HellaSwag, OpenBookQA, and WinoGrande. Higher is better.",source:"https://github.com/facebookresearch/MobileLLM"},
  "Desert Ant Micro-SDKs":{label:"FLORES-200 language ID · 5 words",value:"97.4%",note:"Desert Ant Tongue’s shipped 2 MB int8 artifact over the 20 languages shared with comparison detectors. It is a specialized SDK result, not a score for every Desert Ant model.",source:"https://desertant.com/docs/tongue/"},
  "Whisper Tiny / Base":{label:"LibriSpeech test-clean · WER",value:"5.6% ↓",note:"Whisper tiny.en with greedy decoding in OpenAI’s paper. Lower word error rate is better; the multilingual Tiny and Base variants differ.",source:"https://cdn.openai.com/papers/whisper.pdf"},
  "Picovoice Porcupine":{label:"Wake-word benchmark",value:"Miss rate @ 1 false alarm / 10 h",note:"Picovoice publishes a reproducible six-keyword benchmark plotted at a fixed false-alarm operating point; its repository provides the data and harness rather than a single universal score.",source:"https://github.com/Picovoice/wake-word-benchmark"},
  "Liquid LFM2 / LFM2.5":{label:"GSM8K · accuracy",value:"82.41%",note:"LFM2-2.6B’s reported math result in the LFM2 technical report. This is a checkpoint-level score, not a family-wide claim.",source:"https://arxiv.org/abs/2511.23404"},
  "Mistral NeMo 8B":{label:"MMLU · 5-shot accuracy",value:"70.4%",note:"Mistral-NeMo-Minitron-8B-Instruct, reported by NVIDIA. This checkpoint is a specific compressed variant, not every Mistral NeMo deployment.",source:"https://huggingface.co/nvidia/Mistral-NeMo-Minitron-8B-Instruct"}
};
const mmlu=[{name:"Mistral-NeMo Minitron 8B",score:70.4,source:benchmarks["Mistral NeMo 8B"].source},{name:"Phi-3.5 Mini",score:69,source:benchmarks["Phi-3.5 / Phi-4 Mini"].source},{name:"Llama 3.2 3B",score:63.4,source:benchmarks["Llama 3.2 Mobile"].source}];
document.querySelector('#mmluChart').innerHTML=mmlu.map(item=>`<a class="bar-row" href="${item.source}" target="_blank" rel="noreferrer"><span>${item.name}</span><i><b style="width:${item.score}%"></b></i><strong>${item.score.toFixed(1)}%</strong></a>`).join('');
const charted=new Set(["Llama 3.2 Mobile","Phi-3.5 / Phi-4 Mini","Mistral NeMo 8B"]);
const benchmarkGroups=[
  {title:"General language & reasoning",note:"Listed by reported value; task scores are only comparable when the benchmark and protocol match.",items:["Liquid LFM2 / LFM2.5","SmolLM2","Gemma 2 / Gemma 3n","Qwen 2.5 / Qwen 3","MobileLLM / Pro"]},
  {title:"Multilingual & language ID",note:"Listed by reported value; translation and identification use language-aware evaluation suites.",items:["Desert Ant Micro-SDKs","Tiny Aya"]},
  {title:"Speech recognition",note:"WER is lower-is-better; language, audio quality, and decoder matter.",items:["Cohere Transcribe","Whisper Tiny / Base"]},
  {title:"Wake-word detection",note:"Operational error rates are evaluated at a fixed false-alarm point.",items:["Picovoice Porcupine"]}
];
document.querySelector('#benchmarkGroups').innerHTML=benchmarkGroups.map(group=>`<section class="benchmark-group"><header><h4>${group.title}</h4><p>${group.note}</p></header><div class="benchmark-list">${group.items.map(name=>{const m=models.find(model=>model[0]===name),b=benchmarks[name];return `<a href="${b.source}" target="_blank" rel="noreferrer" class="benchmark-row"><div><b>${m[0]}</b><span>${b.label}</span></div><strong>${b.value}</strong><i>Source ↗</i></a>`}).join('')}</div></section>`).join('');
search.addEventListener('input',()=>{selectedNames=null;render()});ramFilter.addEventListener('change',()=>{selectedNames=null;render()});document.querySelector('#filters').addEventListener('click',e=>{if(!e.target.matches('button'))return;active=e.target.dataset.filter;selectedNames=null;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===e.target));render()});rows.addEventListener('click',e=>{const button=e.target.closest('.model-open');if(button)openDetail(button.dataset.name)});document.querySelectorAll('[data-models]').forEach(button=>button.addEventListener('click',()=>{selectedNames=button.dataset.models.split('|');search.value='';active='all';ramFilter.value='all';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
